version: '3.8'

services:
  app:
    build: .
    ports:
      - "8011:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:

networks:
  appnet:
